### ISSUE TITLE
Not specifying autoReconnectOnUnexpectedDisconnect crashes the SDK

### ISSUE THREAD

**Issue by TheRusskiy** [stripe/stripe-terminal-react-native#532]
**Describe the bug**
When calling `connectBlueToothReader` without `autoReconnectOnUnexpectedDisconnect` there's an exception.
It's probably the same for other "connect reader" methods.

**To Reproduce**

1. Call `connectBlueToothReader` without `autoReconnectOnUnexpectedDisconnect`

**Stripe Terminal React Native SDK version**

`^0.0.1-beta.13`

**Smartphone (please complete the following information):**

- Device: [e.g. Android]

**Additional context**
```
com.facebook.react.bridge.NoSuchKeyException: autoReconnectOnUnexpectedDisconnect

com.facebook.react.bridge.NoSuchKeyException: autoReconnectOnUnexpectedDisconnect
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
	at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:146)
	at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invokeSuspend(StripeTerminalReactNativeModule.kt:227)
	at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invoke(Unknown Source:8)
	at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invoke(Unknown Source:2)
	at com.stripeterminalreactnative.ErrorsKt.withSuspendExceptionResolver(Errors.kt:71)
	at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1.invokeSuspend(StripeTerminalReactNativeModule.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by nazli-stripe** [comment]
@TheRusskiy thanks for reporting this issue, we were able to repro it and a fix is about to be merged. The issue should go away in the next release, till then recommendation is directly passing false if you don't want to turn on auto-reconnect
