### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: autoReconnectOnUnexpectedDisconnect

### ISSUE THREAD

**Issue by NTKrieger** [stripe/stripe-terminal-react-native#554]
**Describe the bug**
App occasionally crashes in production on Android after updating to React Native 0.72.5

**To Reproduce**
Crash results reported in Crashlytics

**Expected behavior**
The app doesn't crash.

**Screenshots**
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: autoReconnectOnUnexpectedDisconnect
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:117)
       at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:149)
       at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invokeSuspend(StripeTerminalReactNativeModule.kt:227)
       at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invoke(:8)
       at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1$1.invoke(:2)
       at com.stripeterminalreactnative.ErrorsKt.withSuspendExceptionResolver(Errors.kt:71)
       at com.stripeterminalreactnative.StripeTerminalReactNativeModule$connectReader$1.invokeSuspend(StripeTerminalReactNativeModule.kt:210)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Stripe Terminal React Native SDK version**

 "react-native": "^0.72.5",
  "@stripe/stripe-terminal-react-native": "^0.0.1-beta.13"

kotlinVersion = "1.7.10"

**Smartphone (please complete the following information):**

- Device: S21 Ultra, S22 Ultra (5g), S23 Ultra
- OS: Android 13

**Additional context**
I know this isn't a lot to go on but it looks to me like someone familiar with the library might recognize fairly quickly.

**Comment by NTKrieger** [comment]
Solved by this commit - would love to see this get a release, but I've patched for now.

https://github.com/stripe/stripe-terminal-react-native/commit/0a7770de195015482be38a14af3d6ce87d2fd2b0

**Comment by nazli-stripe** [comment]
@NTKrieger we are planning for a release next week 🤞, I'll keep this issue open till then in case others run into it as well and want to patch

**Comment by nazli-stripe** [comment]
Fixed in the latest release: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.14
